# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Mrdai\Programming\PyCharm Project2-2019\Cartooning\CartooningGui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 647)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.median_fiflter_value = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.median_fiflter_value.setFont(font)
        self.median_fiflter_value.setObjectName("median_fiflter_value")
        self.gridLayout.addWidget(self.median_fiflter_value, 10, 4, 1, 1)
        self.median_fiflter = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.median_fiflter.setFont(font)
        self.median_fiflter.setAlignment(QtCore.Qt.AlignCenter)
        self.median_fiflter.setObjectName("median_fiflter")
        self.gridLayout.addWidget(self.median_fiflter, 10, 3, 1, 1)
        self.slider_median_fiflter = QtWidgets.QSlider(self.centralWidget)
        self.slider_median_fiflter.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.slider_median_fiflter.setMinimum(1)
        self.slider_median_fiflter.setMaximum(5)
        self.slider_median_fiflter.setSingleStep(1)
        self.slider_median_fiflter.setPageStep(1)
        self.slider_median_fiflter.setProperty("value", 2)
        self.slider_median_fiflter.setOrientation(QtCore.Qt.Horizontal)
        self.slider_median_fiflter.setObjectName("slider_median_fiflter")
        self.gridLayout.addWidget(self.slider_median_fiflter, 10, 5, 1, 1)
        self.slider_bilateral_filter = QtWidgets.QSlider(self.centralWidget)
        self.slider_bilateral_filter.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.slider_bilateral_filter.setMaximum(1)
        self.slider_bilateral_filter.setPageStep(2)
        self.slider_bilateral_filter.setProperty("value", 0)
        self.slider_bilateral_filter.setSliderPosition(0)
        self.slider_bilateral_filter.setOrientation(QtCore.Qt.Horizontal)
        self.slider_bilateral_filter.setObjectName("slider_bilateral_filter")
        self.gridLayout.addWidget(self.slider_bilateral_filter, 13, 5, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 6)
        self.bilateral_filter = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bilateral_filter.setFont(font)
        self.bilateral_filter.setAlignment(QtCore.Qt.AlignCenter)
        self.bilateral_filter.setObjectName("bilateral_filter")
        self.gridLayout.addWidget(self.bilateral_filter, 13, 3, 1, 1)
        self.bilateral_filter_value = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bilateral_filter_value.setFont(font)
        self.bilateral_filter_value.setObjectName("bilateral_filter_value")
        self.gridLayout.addWidget(self.bilateral_filter_value, 13, 4, 1, 1)
        self.slider_subsampled_level = QtWidgets.QSlider(self.centralWidget)
        self.slider_subsampled_level.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.slider_subsampled_level.setMinimum(1)
        self.slider_subsampled_level.setMaximum(4)
        self.slider_subsampled_level.setPageStep(1)
        self.slider_subsampled_level.setProperty("value", 2)
        self.slider_subsampled_level.setOrientation(QtCore.Qt.Horizontal)
        self.slider_subsampled_level.setObjectName("slider_subsampled_level")
        self.gridLayout.addWidget(self.slider_subsampled_level, 10, 2, 1, 1)
        self.button_save_image = QtWidgets.QPushButton(self.centralWidget)
        self.button_save_image.setObjectName("button_save_image")
        self.gridLayout.addWidget(self.button_save_image, 14, 5, 1, 1)
        self.subsampled_level = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.subsampled_level.setFont(font)
        self.subsampled_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.subsampled_level.setAlignment(QtCore.Qt.AlignCenter)
        self.subsampled_level.setObjectName("subsampled_level")
        self.gridLayout.addWidget(self.subsampled_level, 10, 0, 1, 1)
        self.blocksize = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.blocksize.setFont(font)
        self.blocksize.setAlignment(QtCore.Qt.AlignCenter)
        self.blocksize.setObjectName("blocksize")
        self.gridLayout.addWidget(self.blocksize, 13, 0, 1, 1)
        self.blocksize_value = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.blocksize_value.setFont(font)
        self.blocksize_value.setObjectName("blocksize_value")
        self.gridLayout.addWidget(self.blocksize_value, 13, 1, 1, 1)
        self.slider_blocksize = QtWidgets.QSlider(self.centralWidget)
        self.slider_blocksize.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.slider_blocksize.setMinimum(1)
        self.slider_blocksize.setMaximum(5)
        self.slider_blocksize.setSingleStep(1)
        self.slider_blocksize.setPageStep(1)
        self.slider_blocksize.setProperty("value", 4)
        self.slider_blocksize.setOrientation(QtCore.Qt.Horizontal)
        self.slider_blocksize.setObjectName("slider_blocksize")
        self.gridLayout.addWidget(self.slider_blocksize, 13, 2, 1, 1)
        self.subsampled_level_value = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.subsampled_level_value.setFont(font)
        self.subsampled_level_value.setObjectName("subsampled_level_value")
        self.gridLayout.addWidget(self.subsampled_level_value, 10, 1, 1, 1)
        self.button_open_image = QtWidgets.QPushButton(self.centralWidget)
        self.button_open_image.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_open_image.setIconSize(QtCore.QSize(19, 16))
        self.button_open_image.setDefault(False)
        self.button_open_image.setFlat(False)
        self.button_open_image.setObjectName("button_open_image")
        self.gridLayout.addWidget(self.button_open_image, 14, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.median_fiflter_value.setText(_translate("MainWindow", "5"))
        self.median_fiflter.setText(_translate("MainWindow", "中值滤波器大小"))
        self.bilateral_filter.setText(_translate("MainWindow", "双边滤波器选择"))
        self.bilateral_filter_value.setText(_translate("MainWindow", "高斯双边滤波"))
        self.button_save_image.setText(_translate("MainWindow", "保存图片"))
        self.subsampled_level.setText(_translate("MainWindow", "下采样层数"))
        self.blocksize.setText(_translate("MainWindow", "BlockSize"))
        self.blocksize_value.setText(_translate("MainWindow", "9"))
        self.subsampled_level_value.setText(_translate("MainWindow", "2"))
        self.button_open_image.setText(_translate("MainWindow", "打开图片"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

